-- Migration 002 - translate seeded DB content (pages + settings) to English.
-- Runs automatically during update. Idempotent (plain UPDATEs). Single-line values
-- so the migration runner's ";\n" statement splitter is never confused.

UPDATE `{{prefix}}settings` SET setting_value = 'Free Online Gujarati Font Converter' WHERE setting_key = 'site_tagline';
UPDATE `{{prefix}}settings` SET setting_value = 'Gujarati Font Converter - Legacy to Unicode (LMG, Shree Guj, Kruti Dev)' WHERE setting_key = 'default_meta_title';
UPDATE `{{prefix}}settings` SET setting_value = 'Free online Gujarati font converter. Convert LMG, Shree Guj, Saral, Terafont, Akruti and 90+ legacy fonts to Unicode (Shruti) and back.' WHERE setting_key = 'default_meta_description';

UPDATE `{{prefix}}pages` SET title = 'FAQ - Frequently Asked Questions', meta_title = 'FAQ | Gujarati Font Converter', meta_description = 'Frequently asked questions about the Gujarati Font Converter - free limits, privacy, supported fonts and more.', content = '<h2>Frequently Asked Questions</h2><div class="faq-item"><h3>Is this tool free?</h3><p>Yes, conversion up to 200 characters is completely free. For more, see our affordable plans.</p></div><div class="faq-item"><h3>Is my text stored on the server?</h3><p>No. The text you convert is never stored - only the character count is recorded for statistics.</p></div><div class="faq-item"><h3>Which fonts are supported?</h3><p>90+ fonts including LMG, Shree Guj, Saral, Terafont, Akruti, Gujlys, EKLG, Bhasha Bharti, Sulekh and ISM.</p></div><div class="faq-item"><h3>Why should I use a Unicode font?</h3><p>Unicode (Shruti/Nirmala UI) displays on every device, is searchable on Google, and stays readable forever.</p></div>' WHERE slug = 'faq';

UPDATE `{{prefix}}pages` SET title = 'Privacy Policy', meta_title = 'Privacy Policy | Gujarati Font Converter', meta_description = 'Our privacy policy - the text you convert is never stored. Read the details here.', content = '<h2>Privacy Policy</h2><p><strong>Your text:</strong> The text you send for conversion is never stored on our server, never written to any database or log file. Only the character count is recorded for statistical purposes.</p><p><strong>IP Address:</strong> Your IP address is stored temporarily for demo limits and security.</p><p><strong>Cookies:</strong> Used only for sessions and preferences (dark mode, etc.).</p><p><strong>Third parties:</strong> We do not sell any of your data.</p>' WHERE slug = 'privacy-policy';

UPDATE `{{prefix}}pages` SET title = 'Terms of Service', meta_title = 'Terms of Service | Gujarati Font Converter', meta_description = 'Terms and conditions for using the Gujarati Font Converter.', content = '<h2>Terms of Service</h2><p>By using this website you accept the following terms:</p><ul><li>The service is provided on an "as-is" basis.</li><li>100% accuracy of conversion results is not guaranteed - always verify important documents.</li><li>Automated abuse, scraping or bulk requests without the API are prohibited.</li><li>Payments for paid plans are final; learn about the refund policy via the contact page.</li></ul>' WHERE slug = 'terms';

UPDATE `{{prefix}}pages` SET title = 'Font Installation Guide', meta_title = 'Gujarati Font Installation Guide | Font Converter', meta_description = 'How to install Gujarati fonts on Windows and Mac - a simple step-by-step guide.', content = '<h2>How to Install a Gujarati Font</h2><h3>On Windows:</h3><ol><li>Download the font file (.ttf)</li><li>Right-click the file and choose "Install"</li><li>Or copy the file into Control Panel &rarr; Fonts</li></ol><h3>Unicode font (recommended):</h3><p>The Shruti font is already included on Windows. Nirmala UI (Windows 8+) is another great option.</p><h3>On Mac:</h3><ol><li>Double-click the font file</li><li>Press the "Install Font" button</li></ol>' WHERE slug = 'font-installation-guide';

UPDATE `{{prefix}}blog_categories` SET name = 'Tutorials', description = 'Font conversion and typing tutorials' WHERE slug = 'tutorials';
